// <auto-generated />
namespace F2021A6LF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingAudioUploadfortrack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingAudioUploadfortrack));
        
        string IMigrationMetadata.Id
        {
            get { return "202111251922144_adding-AudioUpload-for-track"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
